JarvusInnovations/hologit

.vscode/launch.json, .vscode/tasks.json, README.md, bin/cli.js, commands/source/checkout.js, commands/source/fetch.js, lib/Source.js
- docs: expanded quick start guide in README
- feat: re-implement `git holo source checkout` command
=> Release: hologit v0.5.1

.bldr.toml, .npmignore, commands/lens/exec.js, lib/Lens.js, lib/Studio.js, package-lock.json, package.json
- feat: use bldr API for quick determination of latest stable package
- feat: save and use refspec in lens exec
- fix: install lens package during exec if needed
- fix: disable debug features
=> Release: hologit v0.6.1

lib/Studio.js, package.json
- feat: pull studio image before starting container
=> Release: hologit v0.7.1

lib/Source.js, package.json
- fix: use workspace as HEAD for local sources
=> Release: hologit v0.8.1

commands/source/checkout.js, commands/source/fetch.js, package.json
- fix: update fetch command to use new workspace api
- fix: update checkout command for new workspace api
=> Release: hologit v0.8.2

README.md, docs/grand-tour/installation.md, lib/Repo.js, lib/Studio.js, package-lock.json, package.json
- feat: cleanup studio on death
- feat: add extra bounce protuction for watchman
- fix: always use --all when updating working index
- style: show studio-exec output in info channel
- docs: break out installation section
=> Release: hologit v0.9.2

.vscode/launch.json, .vscode/tasks.json, commands/project.js, lib/Lens.js, lib/Studio.js, package-lock.json, package.json
- refactor: use node-cleanup to handle cleanup runs
- feat: support in-studio habitat execution
- fix: report stderr when git commands fail
=> Release: hologit v0.9.3

.vscode/launch.json, commands/lens/export-tree.js, commands/lens/merge-trees.js, commands/project.js, lib/Projection.js, package.json, plan.sh
- feat: change commit-branch to commit-to and support arbitrary refs
- fix: update export-tree and merge-tree commands
- fix: add watchman to hologit deps
- chore: add revised launch debug configs
=> Release: hologit v0.9.4

README.md, commands/branch/create.js, package-lock.json, package.json, plan.sh
- feat: add holobranch template for emergence-site
- fix: remove watchman from deps, it should come from env
- docs: expand readme intro
- chore: bump git-client version to 1.2.5
=> Release: hologit v0.9.5

commands/project.js, lib/Branch.js, lib/Projection.js, lib/Source.js, package-lock.json, package.json
- fix: prevent pulling tags when fetching sources
- feat: holobranch can extend another holobranch
- feat: allow holobranch config to control default lens value
=> Release: hologit v0.11.0

.npmignore, lib/Branch.js, package.json
- fix: continue allowing holobranches to have no .toml file
=> Release: hologit v0.11.1

.bldr.toml, .vscode/launch.json, README.md, commands/init.js, commands/init.test.js, lenses/sencha-pages/README.md, lenses/sencha-pages/build-pages, lenses/sencha-pages/lens-tree, lenses/sencha-pages/plan.sh, lib/Lens.js, lib/Source.js, package-lock.json, package.json
- docs: improve README introduction
- feat: set up jest for testing
- test: check output of init
- fix: match multi-line console output correctly
- feat: add support for falling back to local package
- feat: add sencha-pages lens
- feat: use local lens package if newer than depot
- chore: bump hab-client required version to 1.0.3
=> Release: hologit v0.13.0

lenses/sencha-app/build-app, lenses/sencha-app/lens-tree, lenses/sencha-app/plan.sh, lib/Lens.js, package-lock.json, package.json
- fix: continue build if pkg lookup fails for any reason but local is available
- style: switch success if/else to bailout
- fix: strip undesired absolute paths from app.json and index.html
=> Release: hologit v0.13.3

package-lock.json, package.json, plan.sh, studio/plan.sh
- chore: lock core/hab dep to 0.79.0
=> Release: hologit v0.13.4

commands/lens/exec.js, lib/Studio.js
- fix: run container with license accepted
- style: add log output during lens install
- fix: apply $relayStderr to container execs
=> Release: hologit v0.13.5

package-lock.json, package.json
- chore: bump package version to 0.13.6
=> Release: hologit v0.13.6

lib/Branch.js, lib/Projection.js, lib/Repo.js, lib/Source.js, lib/TreeObject.js, package-lock.json, package.json
- fix: split source.getHead from source.getOutputTree so fetch works on projected sources
- refactor: use git.getTreeHash method
=> Release: hologit v0.14.1

lib/Branch.js, lib/Projection.js, package-lock.json, package.json
- fix: throw error if before/after layer not found
- fix: support multiple levels of holobranch extension
- fix: use workTree or ref in projection commit message
=> Release: hologit v0.14.3

commands/project.js, package-lock.json, package.json
- fix: update fetch-all code built into project
=> Release: hologit v0.14.4

lib/Mapping.js, lib/Source.js, package-lock.json, package.json
- feat: use any holobranch of any holosource via mapping
=> Release: hologit v0.15.0

commands/lens/exec.js, lib/Branch.js, lib/Lens.js, lib/Projection.js, package-lock.json, package.json
- feat: pass DEBUG env to lens-exec subcommand
- feat: default lens input to '**'
- feat: add external lensing
- fix: use working output tree rather than workspace tree as lens input
- chore: npm update
=> Release: hologit 0.16.0

commands/project.js, lib/Branch.js, lib/Projection.js, lib/Source.js, package-lock.json, package.json
- feat: propagate fetch option upstream during projection
=> Release: hologit v0.17.0

lib/Projection.js, package-lock.json, package.json
- style: prefix projection commits with sun emoji
=> Release: hologit v0.17.1

lib/Branch.js, lib/Lens.js, lib/Workspace.js, package-lock.json, package.json
- feat: support '*' value for before/after configs on mappings and lenses
=> Release: hologit v0.18.0

commands/branch/create.js, lenses/sencha-pages/build-pages, lib/Source.js, package-lock.json, package.json
- feat: use new before: '*' syntax in emergence-site holobranch template
- feat: set after: '*' on top layer in emergence-site template
- feat: support requiring packages in pages build
- feat: enable env source overrides to configure projection
=> Release: hologit v0.19.0

commands/project.js, lib/Branch.js, package-lock.json, package.json
- feat: support listing sources to fetch via param and/or env
=> Release: hologit v0.20.0

lib/TreeObject.js, package-lock.json, package.json
- feat: add TreeObject.getBlobMap method
=> Resease: hologit v0.21.0

lib/Repo.js, package-lock.json, package.json
- fix: filter watchman cookie files out of subscription
=> Release: hologit v0.21.1

lib/TreeObject.js, package-lock.json, package.json
- fix: support reading unicode filenames
=> Release: hologit v0.21.2

lib/TreeObject.js, package-lock.json, package.json
- fix: always use -z now when loading trees
=> Release: hologit v0.21.3

lib/Studio.js, package-lock.json, package.json
- feat: run docker studio commands under current user
- fix: don't persist license
- fix: pass --debug down to sub-commands
=> Release: hologit v0.22.0

commands/lens/exec.js, lib/Repo.js, package-lock.json, package.json
- fix: prevent passing DEBUG=undefined to lens-exec env
- fix: remove extraneous rev-parse that can fail
=> Release: hologit v0.22.1

commands/lens/exec.js, lib/Lens.js, lib/Projection.js, lib/Studio.js, package-lock.json, package.json
- fix: restore output capture for in-process lensing
=> Release: hologit v0.23.1

commands/lens/exec.js, lib/BlobObject.js, lib/Configurable.js, lib/Repo.js, package-lock.json, package.json
- feat: add writeFromFile / writeBlobFromFile methods
- fix: bump yargs to 14.2 to fix issue with hyphenated param
- fix: revert requiring index file internally
- style: rename Configurable class
=> Release: hologit v0.24.0

lib/Studio.js, package-lock.json, package.json
- fix: set STUDIO_TYPE env when running docker container
=> Release: hologit v0.24.1

lib/Repo.js, lib/Source.js, lib/Studio.js, package-lock.json, package.json
- feat: provide CLI feedback while indexing working tree
- fix: reset index.holo before adding --all to avoid cached changes impacting tree
- chore: upgrade dockerode to 3.0.2
=> Release: hologit v0.24.2

lib/Lens.js, lib/Studio.js, lib/TreeObject.js, package-lock.json, package.json
- feat: add support for underlay merge mode
- feat: defer booting studio when discovering package versions
- feat: mount /hab/cache/artifacts
- fix: switch to async-exit-hook to ensure container cleanup completes
- fix: remove anonymous /hab/cache volume
=> Release: hologit v0.25.0

package-lock.json, package.json
- chore: bump git-client to 1.7.0
=> Release: hologit v0.25.1

package-lock.json, package.json
- chore: bump package version to 0.25.2
=> Release: hologit v0.25.2

lib/Lens.js, package-lock.json, package.json
- fix: handle dataTree not existing
=> Release: hologit v0.26.1

package-lock.json, package.json
- fix: bump git-client to v1.7.1
=> Release: hologit v0.26.2

docs/SUMMARY.md, docs/workflows/work-on-sources.md, lib/Projection.js, package-lock.json, package.json
- feat: initialize commit-to ref automatically
- docs: begin work-on-sources chapter
=> Release: hologit v0.27.0

package-lock.json, package.json
- chore: bump package version to 0.28.1
=> Release: hologit v0.28.1

lib/Source.js, package-lock.json, package.json
- fix: use base name for source override env vars
=> Release: hologit 0.28.2

lib/Branch.js, package-lock.json, package.json
- fix: use base source name for matching fetch list
=> Release: hologit 0.28.3

lib/Lens.js, lib/Repo.js, package-lock.json, package.json
- feat: default Repo ref to HEAD
- feat: set HOME for lenses
- fix: check if initial index exists
=> Release: hologit v0.29.0

lib/Studio.js, package-lock.json, package.json
- fix: chown /hab/{cache,pkgs} instead of chmod
- fix: replace busybox tar with gnu tar in studio
=> Release: hologit v0.29.1

lib/Projection.js, lib/Source.js, package-lock.json, package.json
- fix: pass cache to/from through in more cases
=> Release: hologit v0.29.2

lib/Repo.js, package-lock.json, package.json
- feat: enable Repo subclasses
=> Release: hologit v0.29.3

lib/TreeObject.js, package-lock.json, package.json
- fix: use --full-tree when calling ls-tree to ignore cwd
=> Release: hologit v0.29.4

lib/BlobObject.js, package-lock.json, package.json
- feat: support passing - to BlobObject.writeFromFile
=> Release: hologit v0.30.0

lib/Branch.js, lib/Projection.js, lib/TreeObject.js, package-lock.json, package.json
- feat: make TreeObject.deleteChild async and support paths
- chore: fix typo in comment
=> Release: hologit v0.31.0

.holo/config.toml, package-lock.json, package.json, studio/hooks/install, studio/plan.sh
- feat: promote studio service to root and apply /usr/bin/env hack on install
- chore: npm update
=> Release: hologit v0.32.0

lib/TreeObject.js, package-lock.json, package.json
- fix: return existing blobs from writeChild
=> Release: hologit v0.32.1

github-actions/projector/action.yml, github-actions/projector/index.js, package-lock.json, package.json
- feat(projector-action): output commit and tree @themightychris 
- fix: add and use gitExecOutput method @themightychris
=> Release: hologit v0.34.0 

bin/cli.js, commands/init.js, commands/source/create.js, commands/studio.js, github-actions/projector/action.yml, github-actions/projector/package-lock.json, github-actions/projector/post.js, lib/Branch.js, lib/Lens.js, lib/Projection.js, lib/Repo.js, lib/Studio.js, package-lock.json, package.json
- feat(projector-action): add post step @themightychris 
- fix: upgrade logger configuration for winston 3 @themightychris 
- refactor: upgrade logging for winston 3 @themightychris 
- fix: refresh projector package-lock.json @themightychris
=> Release: hologit v0.34.1

.npmignore, github-actions/projector/package-lock.json, github-actions/projector/package.json, package-lock.json, package.json
- chore: bump habitat-action version @themightychris 
- 
- chore: update .npmignore @themightychris
=> Release: hologit v0.34.2

lib/Source.js, package-lock.json, package.json
- feat: automatically re-clone holo index on source reset failure @themightychris 
- chore: npm audit fix @themightychris 
- chore: npm update @themightychris
=> Release: hologit v0.34.3

.github/workflows/docs-site.yml, .holo/branches/docs-site.lenses/mkdocs.toml, .holo/branches/docs-site/_hologit.toml, .studiorc, .vscode/launch.json, README.md, docs/.pages, docs/CNAME, docs/README.md, docs/grand-tour/.pages, docs/grand-tour/README.md, docs/grand-tour/holobranches.md, docs/grand-tour/hololenses.md, docs/grand-tour/holoreactors.md, docs/grand-tour/holosources.md, docs/grand-tour/repository-setup.md, docs/workflows/README.md, mkdocs.yml, package-lock.json, package.json, plan.sh, script/-studio-bootstrap, script/studio
- feat: setup mkdocs site @themightychris 
- docs: add short intro @themightychris 
- docs: fill out initial content @themightychris 
- docs: add features list @themightychris 
- feat: configure CNAME for docs site @themightychris 
- feat: add script/studio @themightychris 
- feat: add mkdocs to studio @themightychris 
- chore: bump to jarvus/node12 @themightychris
=> Release: hologit v0.34.4

.studiorc, lib/Lens.js, package-lock.json, package.json, plan.sh
- fix: fail lensing when tree hash not returned @themightychris 
- fix: update lingering refs to core/node to jarvus/node12 @themightychris
=> Release: hologit v0.34.5

.github/workflows/publish-actions-develop.yml, .github/workflows/publish-actions-v1.yml, .github/workflows/publish-habitat.yml, .github/workflows/publish-website.yml, .studiorc, github-actions/projector/action.yml, lib/Studio.js, package-lock.json, package.json, plan.sh, studio/.dockerignore, studio/Dockerfile, studio/plan.sh
- feat(studio): add optimized Dockerfile @themightychris 
- feat(ci): add publish-habitat workflow @themightychris 
- chore: switch to node14 @themightychris 
- chore: switch default package version to 0.0.1 @themightychris 
- refactor(ci): clean up workflow names @themightychris
=> Release: hologit v0.35.0

.npmignore, lib/Studio.js, plan.sh, studio/Dockerfile, studio/plan.sh
- fix(studio): ensure final files owned by developer group @themightychris 
- fix(studio): link user cache to global @themightychris 
- fix: switch to hab/0.79.0 @themightychris 
- chore: add new files to .npmignore @themightychris
=> Release: hologit v0.35.1

github-actions/projector/action.yml
- fix(action): revert to node12 for action @themightychris
=> Release: hologit v0.35.2

.github/workflows/publish-npm.yml, lib/Studio.js, package-lock.json, package.json
- fix: don't carry host GID into container @themightychris 
- feat(ci): add npm publish @themightychris 
- chore: npm upgrade @themightychris
=> Release: hologit v0.35.3

.github/workflows/publish-npm.yml
- fix: add missing npm version step to workflow @themightychris
=> Release: hologit v0.35.4

github-actions/projector/index.js
- fix(action): force fetch @themightychris
=> Release: hologit v0.35.5 

github-actions/projector/index.js
- fix(action): force source fetch too @themightychris
=> Release: hologit v0.35.6

github-actions/projector/action.yml, github-actions/projector/index.js
- feat(action): add option to skip fetch @themightychris
=> Release: hologit v0.35.7

github-actions/projector/package-lock.json
- chore(action): npm upgrade @themightychris
=> Release: hologit v0.35.8

commands/project.js
- fix: ensure commit retrieved from ref for parentCommit @themightychris
=> Release: hologit v0.35.9

commands/source/ls.js
- feat(ls): improve ls command output; add name and fetch options @themightychris
=> Release: hologit v0.36.0

commands/branch/pull.js, package-lock.json, package.json
- fix(pull): use --no-patch when reading trailers with git-show @themightychris
- chore: upgrade vulnerable packages @themightychris
- chore: npm upgrade @themightychris
=> Release: hologit v0.37.1

.studiorc, github-actions/projector/action.yml, package-lock.json, package.json, plan.sh
Using jarvus build until node20 gets merged into core: https://github.com/habitat-sh/core-plans/pull/4708
=> chore(deps): upgrade to node20
